name             'iojs'
maintainer       'Chris Manson'
maintainer_email 'chris@bloo.ie'
license          'MIT'
description      'Installs/Configures iojs'
long_description 'Installs/Configures iojs'
version          '0.1.0'
